/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GAMZEders10;

import javax.swing.JOptionPane;

/**
 *
 * @author vektorel
 */
public class Ogrenci extends javax.swing.JFrame {

    /**
     * Creates new form Ogrenci
     */
    public Ogrenci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextAdı = new javax.swing.JTextField();
        TextSoyadı = new javax.swing.JTextField();
        TextNo = new javax.swing.JTextField();
        ComboBolum = new javax.swing.JComboBox();
        RButtonErkek = new javax.swing.JRadioButton();
        RButtonKadın = new javax.swing.JRadioButton();
        ButonEkle = new javax.swing.JButton();
        ButonGuncelle = new javax.swing.JButton();
        ButonSil = new javax.swing.JButton();
        ButonSıfırla = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        ButonGetir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(102, 255, 0));
        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bilgiler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.red));
        Panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Panel1ComponentHidden(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("ADI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("SOYADI");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("NO");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("BOLUM");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setText("CİNSİYET");

        TextAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAdıActionPerformed(evt);
            }
        });

        ComboBolum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bilgisayar Müh.", "Makina Müh.", "Elektrik Müh.", "Elohab Müh.", "Jeoloji Müh." }));
        ComboBolum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBolumActionPerformed(evt);
            }
        });

        RButtonErkek.setBackground(new java.awt.Color(102, 255, 0));
        buttonGroup1.add(RButtonErkek);
        RButtonErkek.setText("ERKEK");
        RButtonErkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonErkekActionPerformed(evt);
            }
        });

        RButtonKadın.setBackground(new java.awt.Color(102, 255, 0));
        buttonGroup1.add(RButtonKadın);
        RButtonKadın.setText("KADIN");

        ButonEkle.setText("EKLE");
        ButonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonEkleActionPerformed(evt);
            }
        });

        ButonGuncelle.setText("GÜNCELLE");
        ButonGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonGuncelleActionPerformed(evt);
            }
        });

        ButonSil.setText("SİL");
        ButonSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonSilActionPerformed(evt);
            }
        });

        ButonSıfırla.setText("SIFIRLA");
        ButonSıfırla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonSıfırlaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setText("ID");

        TextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDActionPerformed(evt);
            }
        });

        ButonGetir.setText("GETİR");
        ButonGetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButonGetirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(RButtonErkek)
                                .addGap(18, 18, 18)
                                .addComponent(RButtonKadın))
                            .addComponent(TextNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButonEkle)
                        .addGap(18, 18, 18)
                        .addComponent(ButonGuncelle)
                        .addGap(18, 18, 18)
                        .addComponent(ButonSil)
                        .addGap(18, 18, 18)
                        .addComponent(ButonSıfırla))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButonGetir)
                                .addGap(42, 42, 42)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Panel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButonEkle, ButonGuncelle, ButonSil, ButonSıfırla});

        Panel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        Panel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ComboBolum, RButtonErkek, RButtonKadın, TextAdı, TextID, TextNo, TextSoyadı});

        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonGetir))
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TextNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ComboBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RButtonErkek)
                    .addComponent(RButtonKadın))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonEkle)
                    .addComponent(ButonGuncelle)
                    .addComponent(ButonSil)
                    .addComponent(ButonSıfırla))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel1ComponentHidden

    private void RButtonErkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonErkekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RButtonErkekActionPerformed

    private void TextAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAdıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAdıActionPerformed

    private void ComboBolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBolumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBolumActionPerformed

    private void ButonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonEkleActionPerformed
        // TODO add your handling code here:
//        String adi = TextAdı.getText();
//        TextSoyadı.setText(adi);
        
        String id = TextID.getText();
        String adi = TextAdı.getText();
        String soyadi = TextSoyadı.getText();
        String no = TextNo.getText();
        String bolum = ComboBolum.getSelectedItem().toString();
        String cinsiyet = "";
        
        if( RButtonErkek.isSelected() )
        {
            cinsiyet = "Erkek";
        }
        
        else if( RButtonKadın.isSelected() )
        {
            cinsiyet = "Kadin";
        }
        JOptionPane.showMessageDialog( null, ComboBolum.getSelectedItem().toString() );;
        
        String sorgu="insert into OGRENCI(id,ADI,SOYADI,NO,BOLUM,CINSIYET)"+
                 " values("+id+",\""+adi+"\",\""+soyadi+"\",\""+no+"\",\""+bolum+"\",\""+cinsiyet+"\")";
        DB ekle = new DB();
        int kayit=ekle.islemlerFunction(sorgu);
        if(kayit==1){
                JOptionPane.showMessageDialog(null, "Uyarı", "Kayit Başarlı",1);
        }
    }//GEN-LAST:event_ButonEkleActionPerformed

    private void ButonGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonGuncelleActionPerformed
        // TODO add your handling code here:
        String id = TextID.getText();
        String adi = TextAdı.getText();
        String soyadi = TextSoyadı.getText();
        String no = TextNo.getText();
        String bolum = ComboBolum.getSelectedItem().toString();
        String cinsiyet = "";
        if( RButtonErkek.isSelected() )
        {
            cinsiyet = "Erkek";
        }
        
        else if( RButtonKadın.isSelected() )
        {
            cinsiyet = "Kadin";
        }
        String sorgu = " Update OGRENCI set Adi=\" "+ adi + "\", SoyAdi=\" "+ soyadi + "\", No=\" "+ no + "\" ,Bolum= \" "+ bolum + "\" ,Cinsiyet=\" "+ cinsiyet + "\" where id =\" "+ id + " \"" ;  
        DB guncelle = new DB();
        guncelle.islemlerFunction(sorgu);
    }//GEN-LAST:event_ButonGuncelleActionPerformed

    private void ButonSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonSilActionPerformed
        // TODO add your handling code here:
        String id = TextID.getText();
        
        String sorgu = " Delete from OGRENCI where id =\" "+ id + " \"" ;  
        DB sil = new DB();
        sil.islemlerFunction(sorgu);
    }//GEN-LAST:event_ButonSilActionPerformed

    private void ButonSıfırlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonSıfırlaActionPerformed
        // TODO add your handling code here:
        String sil = "";
        TextID.setText(sil);
        TextAdı.setText(sil);
        TextSoyadı.setText(sil);
        TextNo.setText(sil);
        String cinsiyet = "";

    }//GEN-LAST:event_ButonSıfırlaActionPerformed

    private void TextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIDActionPerformed

    private void ButonGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonGetirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ButonGetirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ogrenci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ogrenci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonEkle;
    private javax.swing.JButton ButonGetir;
    private javax.swing.JButton ButonGuncelle;
    private javax.swing.JButton ButonSil;
    private javax.swing.JButton ButonSıfırla;
    private javax.swing.JComboBox ComboBolum;
    private javax.swing.JPanel Panel1;
    private javax.swing.JRadioButton RButtonErkek;
    private javax.swing.JRadioButton RButtonKadın;
    private javax.swing.JTextField TextAdı;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextNo;
    private javax.swing.JTextField TextSoyadı;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
